name: Cypress Integration Test

on:
  workflow_dispatch:

jobs: 
  cypress-run: 
    runs-on: self-hosted 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v3 
      # Install NPM dependencies, cache them correctly
      # and run all Cypress test
      - name: Cypress run
        uses: cypress-io/github-action@v5 
        with:
          build: npx run cy:run 
          # start: npm start 
