name: Cypress Integration Test

on:
  workflow_dispatch:

jobs: 
  cypress-run: 
    runs-on: ubuntu-20.04 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2 
      # Install NPM dependencies, cache them correctly
      # and run all Cypress test
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.0 
        with:
          build: yarn run cy:run 
          # start: npm start 
